version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install --no-frozen-lockfile
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
